name: eplatform
description: A new Flutter application.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  curved_navigation_bar: ^1.0.3
  circle_nav_bar: ^2.0.1+1
  percent_indicator: ^4.2.3
  dropdown_search: ^5.0.5
  flutter_rating_bar: ^4.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  dotted_border: ^2.0.0+3
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  http: ^0.13.6
  scoped_model: ^2.0.0
  shared_preferences: ^2.1.2
  video_player: ^2.6.1
  auto_orientation: ^2.3.1
  google_maps_flutter: ^2.3.0
  flutter_cached_pdfview: ^0.4.2
  syncfusion_flutter_pdfviewer: ^20.2.43-beta
  pod_player: ^0.1.4
  image_picker: ^1.0.1
  file_picker: ^5.2.8

  zego_uikit: ^2.8.0
  zego_uikit_prebuilt_video_conference: ^2.3.2
  flutter_screenutil: ">=5.5.3+2 <5.6.1"
  flutter_styled_toast: ^2.1.3
  flutter_video_info: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"
  dart_code_metrics: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/teaching logo-1.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
